### PR TITLE
Create Gemfile.rspec-3.1

### PR DESCRIPTION
**Pull request by lucianosousa**
testing against rspec 3.1

### CODE REVIEW

**Comment by lucianosousa** [comment]
@e2 any idea here?

**Comment by e2** [comment]
I don't remember exactly - it was something about RSpec not yet supporting original locations of shared_example calls, see the url in this comment: https://github.com/guard/guard-rspec/blob/master/spec/lib/guard/rspec_formatter_spec.rb#L114

**Comment by lucianosousa** [comment]
broke just using ruby 1.9.3
suggestion?

**Comment by e2** [comment]
"no spec file found for ./spec/support/breadcrumbs.rb:75"

I think I remember this a bit. The specs aren't really good - the file/path operations are not stubbed correctly, so the tests may be failing without a good reason.

You can try reproducing locally with the same RSpec seed: 3825

I think it's just a matter of stubbing File#* Dir#* or Pathname#* methods so that this output/error stops occurring: "no spec file found for ./spec/support/breadcrumbs.rb:75".

I think `spec/requests/breadcrumbs_spec.rb` was supposed to use a shared example defined in `spec/support/breadcrumbs.rb` - so I'm guessing the existence of `spec/requests/breadcrumbs_spec.rb` isn't properly stubbed. But I'm not sure.

**Comment by e2** [comment]
If you rebase this against master, it should work (especially since Ruby 1.9 is EOL and I've removed it).

**Comment by e2** [comment]
I'm closing this, since there were too many RSpec and Ruby versions tested - until RSpec 4.x comes out, it doesn't make sense to support more than the latest available 3.x version (and 2.14 and 2.99 for special reasons).

**Pull request closed without merging**
